//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlParserTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlParserTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid nodes.
        /// </summary>
        internal static string Empty1 {
            get {
                return ResourceManager.GetString("Empty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test, /Test.aspx ACTIVE.
        /// </summary>
        internal static string OneItemActive {
            get {
                return ResourceManager.GetString("OneItemActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;menu&gt;
        ///	&lt;item&gt;
        ///		&lt;displayName&gt;Test&lt;/displayName&gt;
        ///		&lt;path value=&quot;/Test.aspx&quot;/&gt;
        ///	&lt;/item&gt;
        ///&lt;/menu&gt;
        ///.
        /// </summary>
        internal static string OneItemNoSubItems {
            get {
                return ResourceManager.GetString("OneItemNoSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test, /Test.aspx.
        /// </summary>
        internal static string OneItemNotActive {
            get {
                return ResourceManager.GetString("OneItemNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;menu&gt;
        ///	&lt;item&gt;
        ///		&lt;displayName&gt;Home&lt;/displayName&gt;
        ///		&lt;path value=&quot;/Default.aspx&quot;/&gt;
        ///	&lt;/item&gt;
        ///	&lt;item&gt;
        ///		&lt;displayName&gt;Trips&lt;/displayName&gt;
        ///		&lt;path value=&quot;/Requests/Quotes/CreateQuote.aspx&quot;/&gt;
        ///		&lt;subMenu&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;Create Quote&lt;/displayName&gt;
        ///				&lt;path value=&quot;/Requests/Quotes/CreateQuote.aspx&quot;/&gt;
        ///			&lt;/item&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;Open Quotes&lt;/displayName&gt;
        ///				&lt;path value=&quot;/Requests/OpenQuotes.aspx&quot;/&gt;
        ///			&lt;/item&gt;
        ///			&lt;item superOverride=&quot;true [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProvidedSchedAeroMenu {
            get {
                return ResourceManager.GetString("ProvidedSchedAeroMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;menu&gt;
        ///	&lt;id&gt;Wyvern&lt;/id&gt;
        ///	&lt;item&gt;
        ///		&lt;displayName&gt;Home&lt;/displayName&gt;
        ///		&lt;path value=&quot;/mvc/wyvern/home&quot;&gt;&lt;/path&gt;
        ///		&lt;subMenu&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;News&lt;/displayName&gt;
        ///				&lt;path value=&quot;/mvc/wyvern/home/news&quot;&gt;&lt;/path&gt;
        ///			&lt;/item&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;Directory&lt;/displayName&gt;
        ///				&lt;path value=&quot;/Directory/Directory.aspx&quot; /&gt;
        ///				&lt;subMenu&gt;
        ///					&lt;item&gt;
        ///						&lt;displayName&gt;Favorites&lt;/displayName&gt;
        ///						&lt;path value=&quot;/TWR/Directory.aspx&quot; /&gt;
        ///					&lt;/item&gt;
        ///					&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProvidedWyvernMenu {
            get {
                return ResourceManager.GetString("ProvidedWyvernMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, /Default.aspx
        ///Trips, /Requests/Quotes/CreateQuote.aspx
        ///	Create Quote, /Requests/Quotes/CreateQuote.aspx
        ///	Open Quotes, /Requests/OpenQuotes.aspx
        ///	Scheduled Trips, /Requests/Trips/ScheduledTrips.aspx
        ///Company, /mvc/company/view ACTIVE
        ///	Customers, /customers/customers.aspx
        ///	Pilots, /pilots/pilots.aspx
        ///	Aircraft, /aircraft/Aircraft.aspx ACTIVE.
        /// </summary>
        internal static string SchedAeroLastSubActive {
            get {
                return ResourceManager.GetString("SchedAeroLastSubActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, /Default.aspx
        ///Trips, /Requests/Quotes/CreateQuote.aspx ACTIVE
        ///	Create Quote, /Requests/Quotes/CreateQuote.aspx
        ///	Open Quotes, /Requests/OpenQuotes.aspx ACTIVE
        ///	Scheduled Trips, /Requests/Trips/ScheduledTrips.aspx
        ///Company, /mvc/company/view
        ///	Customers, /customers/customers.aspx
        ///	Pilots, /pilots/pilots.aspx
        ///	Aircraft, /aircraft/Aircraft.aspx.
        /// </summary>
        internal static string SchedAeroProvidedExample {
            get {
                return ResourceManager.GetString("SchedAeroProvidedExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, /Default.aspx
        ///Trips, /Requests/Quotes/CreateQuote.aspx ACTIVE
        ///	Create Quote, /Requests/Quotes/CreateQuote.aspx
        ///	Open Quotes, /Requests/OpenQuotes.aspx ACTIVE
        ///	Scheduled Trips, /Requests/Trips/ScheduledTrips.aspx
        ///Company, /mvc/company/view
        ///	Customers, /customers/customers.aspx
        ///	Pilots, /pilots/pilots.aspx
        ///	Aircraft, /aircraft/Aircraft.aspx.
        /// </summary>
        internal static string SchedAeroProvidedExample1 {
            get {
                return ResourceManager.GetString("SchedAeroProvidedExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;menu&gt;
        ///	&lt;item&gt;
        ///		&lt;displayName&gt;FirstTestItem&lt;/displayName&gt;
        ///		&lt;path value=&quot;/test1.aspx&quot;/&gt;
        ///		&lt;subMenu&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;TestSubItem1&lt;/displayName&gt;
        ///				&lt;path value=&quot;FirstTestItem/Tests/SubItems/test1.aspx&quot;/&gt;
        ///			&lt;/item&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;TestSubItem2&lt;/displayName&gt;
        ///				&lt;path value=&quot;FirstTestItem/Tests/SubItems/test2.aspx&quot;/&gt;
        ///			&lt;/item&gt;
        ///			&lt;item&gt;
        ///				&lt;displayName&gt;TestSubItem3&lt;/displayName&gt;
        ///				&lt;path value=&quot;FirstTestItem/Tests/SubItems/test3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThreeItemsEachThreeSubItems {
            get {
                return ResourceManager.GetString("ThreeItemsEachThreeSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstTestItem, /test1.aspx
        ///	TestSubItem1, FirstTestItem/Tests/SubItems/test1.aspx
        ///	TestSubItem2, FirstTestItem/Tests/SubItems/test2.aspx
        ///	TestSubItem3, FirstTestItem/Tests/SubItems/test3.aspx
        ///SecondTestItem, /test2.aspx
        ///	TestSubItem4, SecondTestItem/Tests/SubItems/test4.aspx
        ///	TestSubItem5, SecondTestItem/Tests/SubItems/test5.aspx
        ///	TestSubItem6, SecondTestItem/Tests/SubItems/test6.aspx ACTIVE
        ///ThirdTestItem, /test3.aspx
        ///	TestSubItem7, ThirdTestItem/Tests/SubItems/test7.aspx
        ///	TestSubItem8, ThirdTestI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThreeItemsEachThreeSubItemsSixthSubActive {
            get {
                return ResourceManager.GetString("ThreeItemsEachThreeSubItemsSixthSubActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, /mvc/wyvern/home
        ///	News, /mvc/wyvern/home/news
        ///	Directory, /Directory/Directory.aspx
        ///		Favorites, /TWR/Directory.aspx
        ///		Search Aircraft, /TWR/AircraftSearch.aspx
        ///PASS, /PASS/GeneratePASS.aspx
        ///	Create New, /PASS/GeneratePASS.aspx
        ///	Sent Requests, /PASS/YourPASSReports.aspx
        ///	Received Requests, /PASS/Pending/PendingRequests.aspx
        ///Company, /mvc/company/view ACTIVE
        ///	Users, /mvc/account/list
        ///	Aircraft, /aircraft/fleet.aspx ACTIVE
        ///	Insurance, /insurance/policies.aspx
        ///	Certificate, /Certificates/Cer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WyvernSubActive {
            get {
                return ResourceManager.GetString("WyvernSubActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home, /mvc/wyvern/home ACTIVE
        ///	News, /mvc/wyvern/home/news
        ///	Directory, /Directory/Directory.aspx ACTIVE
        ///		Favorites, /TWR/Directory.aspx
        ///		Search Aircraft, /TWR/AircraftSearch.aspx ACTIVE
        ///PASS, /PASS/GeneratePASS.aspx
        ///	Create New, /PASS/GeneratePASS.aspx
        ///	Sent Requests, /PASS/YourPASSReports.aspx
        ///	Received Requests, /PASS/Pending/PendingRequests.aspx
        ///Company, /mvc/company/view
        ///	Users, /mvc/account/list
        ///	Aircraft, /aircraft/fleet.aspx
        ///	Insurance, /insurance/policies.aspx
        ///	Certificate, /Certifica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WyvernSubSubActive {
            get {
                return ResourceManager.GetString("WyvernSubSubActive", resourceCulture);
            }
        }
    }
}
